# Generated by Django 3.1.5 on 2021-01-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='InterShip',
            options={'ordering': ['-scraped_on']},
        ),
    ]
