# Generated by Django 3.1.5 on 2021-01-12 21:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0002_auto_20210112_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('heading', models.CharField(default='', max_length=100)),
                ('comment', models.TextField(default='', max_length=200)),
                ('scraped_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-scraped_on'],
            },
        ),
        migrations.AlterField(
            model_name='intership',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromWebsite', to='scrapbox.interwebsites'),
        ),
    ]
