# Generated by Django 3.1.5 on 2021-01-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0003_auto_20210112_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='', max_length=6000),
        ),
    ]
