# Generated by Django 3.1.5 on 2021-01-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0004_auto_20210113_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['scraped_on']},
        ),
    ]
